#facebook: "https://facebook.com/atishay811"
#twitter: "https://twitter.com/atishay811"
#github: "https://github.com/atishay"
params.author.email: "j.godlesie@gmail.com"
#linkedin: "https://linkedin.com/in/atishay"
params.author.name: "jgdlws"
#location: San Francisco Bay Area, California
#pinterest:  jgdlws
phone: On request
#hours: "**Mon-Fri:** 9:00AM - 6:00PM, PST"