baseURL: https://jazzymentary.pl
languageCode: "pl"
title: Jazzymentary
theme: eclectic-hugo-theme
disablePathToLower: false
enableRobotsTXT: true
Pagination:
  disableAliases: false
  pagerSize: 10
minify: false

enableEmoji: true

services:
  googleAnalytics:
    id: G-N0BJXX3FZR

sitemap:
    changefreq: "daily"
    priority: 0.5
    filename: "sitemap.xml"
outputs:
  home:
  - html
  - rss
  - json
canonifyURLs: true
markup:
  renderer:
    hardWraps: true
  highlight:
    lineNos: true
  goldmark:
   renderer:
     unsafe: true
