baseURL: jazzymentary.org
languageCode: "pl"
title: Jazzymentary
theme: eclectic-hugo-theme
disablePathToLower: false
enableRobotsTXT: true
googleAnalytics: G-N0BJXX3FZR
Paginate: 3
minify: false

enableEmoji: true

#permalinks:
#  blog: "/blog/:year/:month/:day/:slug"
Paginate: 9

sitemap:
    changefreq: "weekly"
    priority: 0.5
    filename: "sitemap.xml"
outputs:
  home:
  - html
  - rss
  - json
canonifyURLs: true
markup:
  renderer:
    hardWraps: true
  highlight:
    lineNos: true
#enableGitInfo: true
