description: "Wortal o Jazzie"
scss: true
copyright: 2021-{now} jgdlws
color: "000fff"

footer:
  - title: Historie
    recents: histories
    recentCount: 3
  - title: Artyści
    recents: artists
    recentCount: 3
  - title: Albumy
    recents: albums
    recentCount: 3
  - title: Standardy
    recents: standards
    recentCount: 3

outputs:
  home: 
    - html 
    - rss 
    - json

RemoveFormOnSubmission: true